: "${MODEL_NAME:=Llama-2-7b-chat-hf}"

: "${SFT_MODEL_NAME:=${EXP_NAME}-${MODEL_NAME}-${TASK}-sft}"
: "${Q_MODEL_NAME:=${EXP_NAME}-${MODEL_NAME}-${TASK}-Q}"
: "${Q_MODEL_NAME_CHECKPOINT:=${Q_MODEL_NAME}}"

: "${POLICY_MODEL_NAME:=${SFT_MODEL_NAME}}"
: "${POLICY_MODEL_PATH:=${MODEL_PATH%/}/${SFT_MODEL_NAME}}"
: "${TOKENIZER_PATH:=${POLICY_MODEL_PATH}}"

: "${QNET_PATH:=${MODEL_PATH%/}/${Q_MODEL_NAME_CHECKPOINT}}"

: "${AGENT_CONFIG:=sglang}"
: "${CRITIC_BACKEND:=qnet}"

: "${SGLANG_CONTEXT_LENGTH:=4096}"

: "${POLICY_MAX_PROMPT_TOKENS:=3800}"
: "${POLICY_MAX_NEW_TOKENS:=128}"
: "${POLICY_KEEP_FIRST_N:=3}"
: "${POLICY_MIN_TAIL_MSGS:=4}"

: "${POLICY_TEMPERATURE:=0.7}"
: "${POLICY_TOP_P:=1.0}"
: "${POLICY_TOP_K:=-1}"
: "${POLICY_MIN_P:=0.0}"
: "${POLICY_PRESENCE_PENALTY:=0.0}"

: "${QNET_MAX_PROMPT_TOKENS:=3800}"
: "${QNET_CONTEXT_LENGTH:=4096}"
: "${QNET_KEEP_FIRST_N:=3}"
: "${QNET_MIN_TAIL_MSGS:=4}"

: "${SERVER_TP:=1}"